version: '3.8'

services:
  db:
    image: postgres:15
    container_name: karmagrid_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: karmagrid
    ports:
      - "5433:5432"
    volumes:
      - karmagrid_pgdata:/var/lib/postgresql/data

volumes:
  karmagrid_pgdata:
